name: guardian_liveness
description: Implementation of Guardian Liveness SDK from advance.ai.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: lab.neruno.guardian_liveness
        pluginClass: GuardianLivenessPlugin
      ios:
        pluginClass: GuardianLivenessPlugin
